//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Daphne.rc
//
#define IDCANCEL2                       3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDT_REFRESH                     101
#define IDM_KILL                        102
#define IDS_TITLE_VER                   102
#define IDM_FOCUS                       103
#define IDS_WEBURL                      103
#define IDM_ONTOP_ON                    104
#define IDS_URLUPDATES                  104
#define IDM_ONTOP_OFF                   105
#define IDC_KILLCURSOR                  105
#define IDS_WEBDEBUGURL                 105
#define IDM_SER_ON                      106
#define IDS_SUPPORTURL                  106
#define IDM_SER_OFF                     107
#define IDD_PP_LOOK                     107
#define IDS_LICENSE_URL                 107
#define IDM_PROPERTIES                  108
#define IDS_CONTRIBUTEURL               108
#define IDM_SER_CONT                    109
#define IDS_REF_FORMAT                  109
#define IDM_SER_PAUSE                   110
#define IDS_STAT_WEBURL                 110
#define IDS_STAT_WEBURL_S               110
#define IDM_P_FOCUS                     111
#define IDS_STAT_WEBURL_S2              111
#define IDS_STAT_WEBURL_P               111
#define IDM_P_MINIMIZE                  112
#define IDS_WEBURLSTATINFO              112
#define IDM_P_RESTORE                   113
#define IDS_WEBCREDITSURL               113
#define IDM_P_MAXIMIZE                  114
#define IDS_WEBSEARCH                   114
#define IDM_P_HIDE                      115
#define IDS_WEBURLSUPPORT               115
#define IDM_P_SHOW                      116
#define IDS_WEBURLFAQ                   116
#define IDX_ICON                        117
#define IDM_KILLPOLITE                  118
#define IDM_P_MESSAGE                   119
#define IDT_SERVICES                    120
#define WM_K_BYNAME                     121
#define WM_K_BYNAMEP                    122
#define IDM_P_ONTOP_ON                  123
#define IDM_P_ONTOP_OFF                 124
#define IDT_UPDATELIST                  125
#define WM_K_TARGET                     126
#define WM_K_INSPECTOR                  127
#define IDR_MAINFRAME                   128
#define IDM_INJSA                       128
#define IDB_DAPHNE                      129
#define IDM_RMVSA                       129
#define IDM_CPY_NAME                    130
#define IDD_PROPERTIES                  130
#define IDD_SENDMSG                     131
#define IDM_CPY_PATH                    131
#define IDD_SETTINGS                    132
#define IDM_CPY_PATHARGS                132
#define IDD_KILLALL                     133
#define IDM_CPY_PID                     133
#define IDD_KMI_EDIT                    134
#define IDM_SPC_RT                      134
#define WM_K_KILLER                     135
#define IDM_SPC_HI                      135
#define IDM_SPC_NO                      136
#define IDM_SPC_LO                      137
#define IDM_P_TSUSPEND                  138
#define IDM_P_TRESUME                   139
#define IDM_P_TTERMINATE                140
#define IDM_SPT_AN                      141
#define IDM_SPT_TC                      142
#define IDM_SPT_NO                      143
#define IDM_SPT_BN                      144
#define IDM_SPT_ID                      145
#define IDM_SPT_HI                      146
#define IDM_SPT_LO                      147
#define WM_K_RUNPAS                     148
#define WM_K_RUNP                       149
#define IDM_P_THIDE                     150
#define IDM_P_TSHOW                     151
#define IDM_TASKS                       152
#define IDM_P_MKRESIZE                  153
#define IDM_P_NOCAPTION                 154
#define IDM_P_CAPTION                   155
#define IDM_NEWTRAP                     156
#define IDM_DRK_SUBMIT                  157
#define IDM_DRK_LOOKUP                  158
#define IDT_SCHEDULER                   159
#define WM_DRK_UNHIDE                   160
#define WM_DRK_UNHIDE_END               198
#define WM_K_KILLER_END                 199
#define IDD_GETVALUE                    200
#define IDM_AFFINITY                    201
#define IDI_NULL                        203
#define IDD_INSPECTOR                   204
#define IDR_MAINFRAME1                  204
#define IDC_LUPA                        205
#define IDR_MAINFRAME2                  205
#define IDR_MAINFRAME3                  206
#define IDR_MAINFRAME4                  207
#define IDC_REDKILLCURSOR               208
#define IDR_MAINFRAME5                  208
#define IDC_T_ENABLE                    209
#define IDR_MAINFRAME6                  209
#define IDC_T_DISABLE                   210
#define IDR_MAINFRAME7                  210
#define IDC_T_ONTOP                     211
#define IDR_MAINFRAME8                  211
#define IDC_T_ONTOPOFF                  212
#define IDR_MAINFRAME9                  212
#define IDD_KMI_CPLIST                  213
#define IDR_MAINFRAME10                 213
#define IDR_MAINFRAME0                  214
#define IDD_PP_KILL                     214
#define IDD_PP_STARTUP                  215
#define IDD_CRASH                       217
#define IDD_RUNP                        218
#define IDD_AUTHUSER                    219
#define IDD_WNDLIST                     221
#define IDC_T_HIDE                      222
#define IDD_PP_ADVANCED                 222
#define IDC_T_SELECT                    223
#define IDD_MB_WEBAGREE                 224
#define IDD_NEW_TRAP                    227
#define IDD_PP_TRAPS                    228
#define IDD_PP_HIGHLIGHTS               229
#define IDD_PTREE_DLG                   230
#define WM_K_PTREE                      231
#define IDD_LSSOFT_DIALOG               232
#define WM_K_ISOFT                      233
#define WM_K_CPUUSAGE                   234
#define IDP_SOCKETS_INIT_FAILED         235
#define IDD_SOFTPROPERTIES              236
#define IDM_P_CLOSE                     237
#define IDD_WNDCLOSEALL                 237
#define WM_K_WNDCLOSE                   238
#define IDD_PP_MULTIDESK                238
#define IDD_SPLASH_DESKTOP              241
#define IDM_KILLPOLITEAT                243
#define IDM_KILLAT                      244
#define IDD_KILLAT                      245
#define WM_K_SCHEDULE_OFF               246
#define IDD_SHUTDOWN                    247
#define IDM_TASK_REMOVE                 248
#define IDD_SCHEDULED                   249
#define WM_K_SCHEDULED                  250
#define IDD_GREEN                       251
#define IDD_CPUUSAGEH                   254
#define IDD_PP_LOGGING                  255
#define IDC_CURSOR1                     278
#define IDC_CURSOR2                     279
#define IDC_CURSOR3                     280
#define IDC_CURSOR4                     281
#define IDC_CURSOR5                     282
#define IDC_CURSOR6                     283
#define IDC_CURSOR7                     284
#define IDC_CURSOR8                     285
#define IDB_BITMAP1                     286
#define IDI_ICON1                       287
#define IDI_ICON2                       288
#define IDI_ICON3                       289
#define IDI_ICON4                       290
#define IDI_ICON5                       291
#define IDI_ICON6                       292
#define IDI_ICON7                       293
#define IDI_ICON8                       294
#define IDI_ICON9                       295
#define IDI_ICON10                      296
#define IDI_ICON11                      297
#define IDI_ICON12                      298
#define IDI_ICON13                      299
#define WM_K_GOD                        300
#define WM_K_PSR                        301
#define IDD_DIALOG1                     301
#define IDD_AFFINITY                    301
#define WM_K_COPYLIST                   302
#define IDM_UNUSED1                     303
#define IDM_UNUSED2                     304
#define IDD_WINDOWSIZE                  305
#define IDD_MESSAGEAT                   306
#define WM_K_SCHEDULE_MSG               307
#define IDC_T_SIZE                      308
#define IDD_DAPHNE_DIALOG               309
#define IDM_CPY_MD5                     310
#define IDM_CPY_SHA1                    311
#define IDD_LISTLS                      1000
#define IDC_LIST                        1001
#define IDC_WWW                         1002
#define IDC_FULLPATHEX                  1003
#define IDC_TITLE                       1004
#define IDC_LSTITLE                     1004
#define IDC_P_NAME                      1004
#define IDC_P_PATH                      1005
#define IDC_VERSION                     1006
#define IDC_LSVERSION                   1006
#define IDC_P_PRIORITY                  1006
#define IDC_PUBLISHER                   1007
#define IDC_LSPUBLISHER                 1007
#define IDC_P_CLASS                     1007
#define IDC_LSWEB                       1008
#define IDC_P_CREATED                   1008
#define IDC_RAW                         1009
#define IDC_LSRAW                       1009
#define IDC_P_KERNELT                   1009
#define IDC_P_USERT                     1010
#define IDC_P_THREADS                   1011
#define IDC_P_PARENT                    1012
#define IDC_T_WNDS                      1013
#define IDC_GOOGLE                      1014
#define IDC_M_MSG                       1015
#define IDC_M_LPARAM                    1016
#define IDC_M_WPARAM                    1017
#define IDC_F_REFRESH                   1018
#define IDC_SETTINGS                    1019
#define IDC_ABOUT                       1020
#define IDC_WNDALPHA                    1021
#define IDC_MENUB                       1022
#define IDC_KA_NAME                     1023
#define IDC_KILLERS                     1024
#define IDC_S_ADD                       1025
#define IDC_S_EDIT                      1026
#define IDC_S_REMOVE                    1027
#define IDC_KMI_NAME                    1028
#define IDC_KMI_PLIST                   1029
#define IDC_S_UP                        1031
#define IDC_S_DOWN                      1032
#define IDC_AONTOP                      1033
#define IDC_S_UP2                       1033
#define IDC_S_DOWN2                     1034
#define IDC_V_LIST                      1035
#define IDC_GETVAL1                     1036
#define IDC_GETVAL2                     1037
#define IDC_V_FILTER                    1037
#define IDC_C_KILL                      1039
#define IDC_LUPACTRL                    1040
#define IDC_I_TITLE                     1042
#define IDC_I_CLASS                     1043
#define IDC_I_TEXT                      1044
#define IDC_S_COLUMNS                   1045
#define IDC_TACTION                     1047
#define IDC_P_INFOT                     1049
#define IDC_P_INFOM                     1050
#define IDC_P_INFOE                     1051
#define IDC_P_INFOIO                    1052
#define IDC_KMI_PROCS                   1053
#define IDC_S_TRANSP                    1055
#define IDC_PS_25                       1056
#define IDC_PS_100                      1057
#define IDC_AB_TITLE                    1058
#define IDC_S_START_WIN                 1059
#define IDC_S_START_HIDE                1060
#define IDC_WEB                         1061
#define IDC_LICENSE                     1062
#define IDC_KA_CASE                     1063
#define IDC_CR_ERROR                    1065
#define IDC_P_THREADLIST                1070
#define IDC_R_PRG                       1071
#define IDC_R_ARG                       1072
#define IDC_R_DIR                       1073
#define IDC_EXPLORE                     1074
#define IDC_EXPLORE2                    1075
#define IDC_RP_SUSP                     1076
#define IDC_A_USER                      1077
#define IDC_A_PASSWD                    1078
#define IDC_STT_BUGS                    1079
#define IDC_STG_CONTRIB                 1080
#define IDC_STT_THANKS                  1081
#define IDC_STT_USERN                   1082
#define IDC_STT_PASSW                   1083
#define IDC_STT_EXCEP                   1084
#define IDC_STT_STAR                    1085
#define IDC_STG_ERRINFO                 1086
#define IDC_STT_FILTER                  1087
#define IDC_STT_DRAG                    1088
#define IDC_STT_TITLE                   1089
#define IDC_STT_CLASS                   1090
#define IDC_STT_TEXT                    1091
#define IDC_STT_PROC                    1092
#define IDC_STT_MENU                    1093
#define IDC_STG_PROCL                   1094
#define IDC_STG_DMENU                   1095
#define IDC_STT_MAINW                   1096
#define IDC_STG_PROCLC                  1097
#define IDC_STG_STARTU                  1098
#define IDC_STT_1                       1099
#define IDC_STT_2                       1100
#define IDC_STT_3                       1101
#define IDC_STT_4                       1102
#define IDC_STT_5                       1103
#define IDC_STT_6                       1104
#define IDC_STT_7                       1105
#define IDC_STG_WNDS                    1106
#define IDC_STG_MI                      1107
#define IDC_STT_PRG                     1108
#define IDC_STT_ARG                     1109
#define IDC_STT_DIR                     1110
#define IDC_STT_MSG                     1111
#define IDC_STT_LP                      1112
#define IDC_STT_WP                      1113
#define IDC_STT_LOC                     1114
#define IDC_STT_SZ                      1115
#define IDC_I_LOCATION                  1116
#define IDC_I_SIZE                      1117
#define IDC_WNDS                        1119
#define IDC_STG_BEHAVE                  1120
#define IDC_S_SELECTD                   1121
#define IDC_S_ALT_BKGND                 1121
#define IDC_S_HIDEZOMBIES               1122
#define IDC_S_CHECKUP                   1124
#define IDC_S_PROXY                     1125
#define IDC_S_PADDR                     1126
#define IDC_S_PPORT                     1127
#define IDC_STS_PROXY                   1128
#define IDC_SC_SHIFT                    1129
#define IDC_SC_ALT                      1130
#define IDC_SC_VKEY                     1131
#define IDC_STG_SC                      1132
#define IDC_SC_ON                       1134
#define IDC_STT_NOTE                    1135
#define IDC_STT_Q                       1136
#define IDC_S_FASTR                     1137
#define IDC_ADV_UNHIDE                  1139
#define IDC_SC_CTRL                     1143
#define IDC_NAME                        1144
#define IDC_STT_PNAME                   1145
#define IDC_TRAP                        1146
#define IDC_STT_TYPE                    1147
#define IDC_STG_TRAPS                   1150
#define IDC_TR_LIST                     1151
#define IDC_TR_ADD                      1152
#define IDC_TR_EDIT                     1153
#define IDC_TR_REMOVE                   1154
#define IDC_STT_TRANS_IT                1155
#define IDC_STT_TRANS_DE                1156
#define IDC_TR_WCONTAINS                1156
#define IDC_STT_TRANS_FR                1157
#define IDC_STT_WCONT                   1157
#define IDC_STT_TRANS_DE2               1158
#define IDC_STT_TRANS_VA                1158
#define IDC_STT_TRANS_PL                1159
#define IDC_STT_TRANS_RU                1160
#define IDC_HL_LIST                     1161
#define IDC_STT_TRANS_PT                1161
#define IDC_STT_HLLIST                  1162
#define IDC_STT_TRANS_JA                1162
#define IDC_STT_TRANS_AR                1163
#define IDC_HL_PROCS                    1164
#define IDC_STT_TRANS_EL                1164
#define IDC_HL_HLSYSTEM                 1165
#define IDC_HL_HLTOP                    1166
#define IDC_HL_HLTOPMEM                 1167
#define IDC_ADV_JAVAHIDE                1168
#define IDC_CHECKDEBUG                  1169
#define IDC_INF_CPU                     1170
#define IDC_INF_MEM                     1171
#define IDC_INF_CPUC                    1172
#define IDC_INF_FMEM                    1173
#define IDC_STORE_INI                   1174
#define IDC_STORE_REG                   1175
#define IDC_STG_STRCFG                  1176
#define IDC_STT_PARENT                  1177
#define IDC_TREE                        1178
#define IDC_STT_NOUPDATE                1179
#define IDM_UNINSTALL                   1182
#define IDC_LISTLS                      1183
#define IDC_ST_LSVER                    1190
#define IDC_ST_LSPUB                    1191
#define IDC_ST_LSWEB                    1192
#define IDC_ST_LSRAWT                   1193
#define IDC_STT_WND                     1194
#define IDC_WCA_NAME                    1195
#define IDC_WCA_CASE                    1196
#define IDC_SCMD_ON                     1197
#define IDC_STG_MD                      1198
#define IDC_SPIN_ED                     1200
#define IDC_STED_NUM                    1201
#define IDC_CTRL_EDN                    1202
#define IDC_SPL_TXT                     1203
#define IDC_SUPPORT                     1205
#define IDC_STT_TRANS_CH                1206
#define IDC_STT_CONTR_CH                1207
#define IDC_TIME                        1209
#define IDC_DATE                        1210
#define IDC_BE_POLITE                   1211
#define IDC_STT_SELECTKA                1212
#define IDC_STT_PTK                     1213
#define IDC_PNAME                       1214
#define IDC_TYPE                        1215
#define IDC_TASKS                       1217
#define IDC_STT_GREEN                   1218
#define IDC_STG_IN                      1219
#define IDC_CONTEXTMENU_ON              1220
#define IDC_S_ANIMICON                  1221
#define IDC_GRAPH                       1222
#define IDC_STINFO                      1223
#define IDC_TFACTOR                     1224
#define IDC_CONTRIBUTE                  1225
#define IDC_P_OWNER                     1226
#define IDC_STT_OWNER                   1227
#define IDC_STG_LOG                     1228
#define IDC_PPL_LOGP                    1229
#define IDC_PPL_LOGPF                   1230
#define IDC_PPL_LOGPS                   1231
#define IDC_CU_UPHY                     1232
#define IDC_CU_TPHY                     1233
#define IDC_CU_STA                      1234
#define IDC_CU_UPHY_T                   1235
#define IDC_CU_TPHY_T                   1236
#define IDC_CU_SYSC_T                   1237
#define IDC_CU_SYSC                     1238
#define IDC_CU_MEMK_T                   1239
#define IDC_CU_MEMK                     1240
#define IDC_CU_THR_T                    1255
#define IDC_CU_THR                      1256
#define IDC_CU_PRO_T                    1257
#define IDC_CU_PRO                      1258
#define IDC_CU_HND_T                    1259
#define IDC_CU_HND                      1260
#define IDC_LSSOFT_EXPORT               1261
#define IDC_CU_PRO2                     1261
#define IDC_CU_PAGE                     1261
#define IDC_INF_COUNT                   1262
#define IDC_INF_LOGIN                   1263
#define IDC_INF_CPUCOUNT                1264
#define IDC_INF_PROC                    1265
#define IDC_CHECK1                      1267
#define IDC_SEND_ANON_STAT              1267
#define IDC_TRAP_AFFINITY               1267
#define IDC_STG_ASTAT                   1268
#define IDM_DRK_OPENFOLDER              1270
#define IDC_CREDITS                     1271
#define IDC_LIST1                       1271
#define IDC_CPULIST                     1271
#define IDC_CPUALL                      1272
#define IDC_CPUNONE                     1273
#define IDC_STG_RUNSLOTS                1274
#define IDC_EDIT2                       1276
#define IDC_RS_F4                       1276
#define IDC_RS_F3                       1277
#define IDC_GEN64INT                    1277
#define IDC_SETSIZE                     1277
#define IDC_RS_F2                       1278
#define IDC_STT_GEN64INT                1278
#define IDC_RS_F1                       1279
#define IDC_PRESIZE                     1279
#define IDC_STT_WS_NEWSIZE              1280
#define IDC_STT_WS_PREDEF               1281
#define IDC_STT_MESSAGE                 1282
#define IDC_STT_MMWS                    1282
#define IDC_STT_SELECTMA                1283
#define IDC_STT_SLASH                   1283
#define IDC_EDIT1                       1284
#define IDC_MSGATMSG                    1284
#define IDC_P_MINWS                     1284
#define IDC_P_MAXWS                     1285
#define IDC_BUTTON1                     1286
#define IDC_CU_PAGE_T                   1287

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        312
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1288
#define _APS_NEXT_SYMED_VALUE           169
#endif
#endif
